#!/usr/bin/env node
// Converts the plain-text transcriptions in data/raw/ into browser-loadable
// book files in data/books/. Run: npm run build:data
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// One entry per book. `raw` is the transcription, the rest is metadata.
const BOOKS = [
  {
    id: 'korean-1000',
    raw: 'data/raw/korean-1000.txt',
    title: '1000 Câu Tiếng Hàn Thông Dụng Nhất',
    subtitle: '1000 most common Korean sentences',
    language: 'Korean',
    ttsLang: 'ko-KR',
    meaningLang: 'vi',
  },
];

function parseBook(text) {
  const chapters = [];
  let current = null;
  text.split(/\r?\n/).forEach((line, i) => {
    if (!line.trim() || line.startsWith('# ')) return;
    const parts = line.split('|');
    if (line.startsWith('## ')) {
      const [no, title, native] = line.slice(3).split('|');
      current = { id: Number(no), title: title.trim(), titleNative: (native || '').trim(), items: [] };
      chapters.push(current);
      return;
    }
    if (parts.length !== 4 || !current) {
      throw new Error(`Line ${i + 1}: expected "no|text|romanization|meaning", got: ${line}`);
    }
    const [n, t, rom, meaning] = parts.map((p) => p.trim());
    current.items.push({ n: Number(n), text: t, rom, meaning });
  });
  return chapters;
}

function build() {
  for (const book of BOOKS) {
    const chapters = parseBook(fs.readFileSync(path.join(ROOT, book.raw), 'utf8'));
    const numbers = chapters.flatMap((c) => c.items.map((it) => it.n));
    numbers.forEach((n, i) => {
      if (n !== i + 1) throw new Error(`${book.id}: item #${i + 1} is numbered ${n}`);
    });
    const { raw, ...meta } = book;
    const out = { ...meta, itemCount: numbers.length, chapters };
    const js =
      '// Generated by scripts/build-books.js from ' + raw + ' - do not edit by hand.\n' +
      'window.LT_BOOKS = window.LT_BOOKS || [];\n' +
      'window.LT_BOOKS.push(' + JSON.stringify(out) + ');\n';
    fs.writeFileSync(path.join(ROOT, 'data/books', book.id + '.js'), js);
    console.log(`${book.id}: ${chapters.length} chapters, ${numbers.length} items`);
  }
}

module.exports = { parseBook };
if (require.main === module) build();
